<a href="https://colab.research.google.com/github/shreeprasadbhat/matrix-theory/blob/master/others/find_rref_and_inverse.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Write a python program to reduce any given matrix to the row-reduced echelon form. Use this to compute inverse of the matrix.


In [20]:
import numpy as np
import copy

# Input number of rows and columns in matrix
#nRows = int(input('Enter the number of rows in matrix : '))
#nCols = int(input('Enter the number of columns in matrix : '))

nRows = 3
nCols = 3

# Input the elements of matrix
#print('Enter the elements of matrix in single line seperated by spaces\n')
#entries = [float(i) for i in input().split()]
#entries = [2.0, 1, 1, 4, -6, 0, -2, 7, 2]
#entries = [1, 2, 3, 2, 4, 5, 3, 5, 6] # row interchange
#entries = [1, 2, 1, -2, 1, 8, 1, -2, -7] # inverse does not exist
entries = [2.0, 1, 1, 2, 0, 0, 0, 0, 2]

# Convert elements to numpy array form
matrix = np.array(entries).reshape(nRows, nCols)

np.set_printoptions(precision=3, suppress=True)

rref = matrix.copy()

if nRows == nCols:
  # Also find inverse of matrix if it is square matrix
  isSquareMatrix = True

  # Initialize inverse of matrix to identity matrix of order [nRows, nCols]
  inverse_matrix = np.identity(nRows)

for i in range(min(nRows, nCols)):

  #ipdb.set_trace()

  # check for pivot column or free column
  if rref[i, i] == 0 and i != nRows:
    isFreeColumn = True
    # if pivot is zero, interchange with next row whose pivot is not zero
    for jRow in range(i+1, nRows):
      # check if pivot of this row is zero
      if rref[jRow, jRow] == 0 :
        continue
      else :
        isFreeColumn = False

        # row interchange
        temp = copy.deepcopy(rref[i,:])
        rref[i, :] = copy.deepcopy(rref[jRow,:])
        rref[jRow,:] = copy.deepcopy(temp)
        
        # also, do corresponding row interchange in inverse matrix
        if isSquareMatrix :
          temp = copy.deepcopy(inverse_matrix[i,:])
          inverse_matrix[i,:] = copy.deepcopy(inverse_matrix[jRow, :])
          inverse_matrix[jRow, :] = copy.deepcopy(temp)
        break

    if isFreeColumn :
      # skip this column and move on to next column for row reduction
      continue
  
  pivot =  rref[i, i]

  # divide 1st row by 1st column entry to make 1st column entry 1
  rref[i, :] = rref[i, :] / pivot

  if isSquareMatrix:
    inverse_matrix[i, :] = inverse_matrix[i, :] / pivot

  for iRow in range(i+1, nRows, 1):

    scalar = rref[iRow, i]

    # Row reduction
    rref[iRow,:] = rref[iRow,:] - scalar * rref[i, :]

    if isSquareMatrix:
      inverse_matrix[iRow,:] = inverse_matrix[iRow,:] - scalar * inverse_matrix[i, :]

# print row- reduce echelon form of matrix
print('Row reduced echelon form of given matrix is\n')
print(np.array(rref))

if isSquareMatrix :
  # continue code for finding inverse

  # check if inverse exists for matrix, i.e check all zero exists in rref
  existsInverse = True
  for iRow in range(nRows) :
    if np.all(rref[iRow, :] == 0) :
      existsInverse = False
      break

  if existsInverse :
    # continue doing row reduction
    for iRow in range(nRows-2, -1, -1):
      for iCol in range(nCols-1,  iRow, -1):
        if rref[iRow, iCol] == 0 :
          continue
        # Row reduction
        scalar = rref[iRow, iCol]
        rref[iRow, :] = rref[iRow, :] - scalar * rref[iCol, :]
        inverse_matrix[iRow, :] = inverse_matrix[iRow, :] - scalar * inverse_matrix[iCol, :]

    # print inverse of matrix
    print('\nInverse of given matrix is\n')
    print(np.array(inverse_matrix))
  else :
    print('\nInverse does not exists for given square matrix\n')
else :
  print('\nInverse does not exist for non-square matrix\n')

Row reduced echelon form of given matrix is

[[ 1.   0.5  0.5]
 [-0.   1.   1. ]
 [ 0.   0.   1. ]]

Inverse of given matrix is

[[ 0.   0.5  0. ]
 [ 1.  -1.  -0.5]
 [ 0.   0.   0.5]]
